### ISSUE TITLE
Not resume playing music

### ISSUE THREAD

**Issue by Marc1979** [denniedegroot/com.google.tts#2] opened 2019-01-31 07:26 UTC
I don't know if it is possible to change this.
If I'm playing a radiostream on my google home mini's and I send a broadcast message to the mini's (from a assistant on a phone), the music is muted an un-muted after the message is spoken.
If i use you're app (broadcast something from homey), the music is stopped and not resumed..

Is this something that can be changed? So the mini's resumed to play the already streamed radiostation.

**Comment by denniedegroot** [comment] 2019-01-31 16:06
I am not sure if this is possible. I will look into it when I have time.

**Comment by JohanBendz** [comment] 2019-02-14 06:52
This is not a bug, Sonos have the same issues. When you send a new stream (say Spotify) to a speaker the currently streamed source will be replaced by the new one. Google handle interuptions of the streamed content well if done within their environment (broadcast and notifications) but not when you change stream.

**Comment by Marc1979** [comment] 2019-02-14 17:47
@JohanBendz
That makes clear...the speech from the TTS app is a stream and not a broadcast.
Thanks for the clear answer

**Comment by denniedegroot** [comment] 2019-02-14 22:15
Just tested this and there seems to be no way to get the previous stream and resume it unfortunately.
So I will close this issue as not fixable.

**Closed by denniedegroot** 2019-02-14 22:15 UTC
Labels: bug
